

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace StokTakip_Deneme_.Models.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Kullanicilar
    {
        public int ID { get; set; }

        [Required(ErrorMessage = " Bu Alan boþ geçilemez")]
        public string KullaniciAdi { get; set; }
        [Required(ErrorMessage = " Bu Alan boþ geçilemez")]
        public string Sifre { get; set; }
        [Required(ErrorMessage = " Bu Alan boþ geçilemez")]
        public string Rol { get; set; }
        [Required(ErrorMessage = " Bu Alan boþ geçilemez")]
        public string AdiSoyadi { get; set; }
        [Required(ErrorMessage = " Bu Alan boþ geçilemez")]
        public string Telefon { get; set; }
        [Required(ErrorMessage = " Bu Alan boþ geçilemez")]
        public string Adres { get; set; }
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$",
            ErrorMessage = "Lütfen uygun formatta e-mail adresi giriniz.")]
        public string Email { get; set; }
        [Required(ErrorMessage = " Bu Alan boþ geçilemez")]
        public System.DateTime Tarih { get; set; }
    }
}
