//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip_Deneme_.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int ID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> SepetID { get; set; }
        public string BarkodNo { get; set; }
        public Nullable<decimal> BirimFİyati { get; set; }
        public Nullable<decimal> Miktari { get; set; }
        public Nullable<decimal> ToplamFiyati { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<int> Birim { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> saat { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
