
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace StokTakip_Deneme_.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {

            this.MarkaListesi = new List<SelectListItem>();
            MarkaListesi.Insert(0, new SelectListItem { Text = "Önce Kategori Bölümünü Seçiniz ", Value = "" });

        }

        public int ID { get; set; }
        [Required(ErrorMessage = " Kategori Alaný boþ geçilemez")]
        public int KategoriID { get; set; }
        [Required(ErrorMessage = " Marka Alaný boþ geçilemez")]
        public int MarkaID { get; set; }
        [Required(ErrorMessage = " Ürün Adý boþ geçilemez")]
        public string UrunAdi { get; set; }
        [Required(ErrorMessage = " Barkod No  boþ geçilemez")]
        public string BarkodNo { get; set; }
        [Required(ErrorMessage = " Alýþ Fiyatý boþ geçilemez")]
        public decimal AlisFiyati { get; set; }
        [Required(ErrorMessage = " Satýþ Fiyatý  boþ geçilemez")]
        public decimal SatisFiyati { get; set; }
        [Required(ErrorMessage = " KDV Alaný boþ geçilemez")]
        public int KDV { get; set; }
        [Required(ErrorMessage = " Birim Alaný boþ geçilemez")]
        [Range(0, 100, ErrorMessage = "0 ila 100 arasýnda bir KDV deðeri girilmelidir")]
        public int BirimID { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = " Tarih Kýsmý  boþ geçilemez")]
        public System.DateTime Tarih { get; set; }

        [Required(ErrorMessage = " Açýklama Alaný boþ geçilemez")]
        public string Aciklama { get; set; }
        [Required(ErrorMessage = " Ürün Miktarý  boþ geçilemez")]
        public decimal Miktari { get; set; }

        public virtual Birimler Birimler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Markalar Markalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
         public virtual ICollection<Satislar> Satislar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public List<SelectListItem> KategoriListesi { get; set; }
        public List<SelectListItem> MarkaListesi { get; set; }

        public List<SelectListItem> BirimListesi { get; set; }
    }
}
